[tool.black]
line-length = 80
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 80

[tool.ruff]
line-length = 80
# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]
ignore = ["E501", "E741"]

#[flake8]
#max-line-length = 80
#ignore = ['E501', 'W503']
#per-file-ignores = config/settings/*:F405 F403 F401